var height=0; var width=0; var h2=0; var w2=0;
function winsizedir(wtran) {
    wtran = wtran.toLowerCase();
    if (wtran == "projstandardcsscad") { height = 19.0; width = 28; return; }
    if (wtran == "projstandardcsspsq") { height = 20.5; width = 29; return; }
    if (wtran == "projstandardcssbluecad") { height = 19.0; width = 28; return; }
    if (wtran == "projstandardcssbluepsq") { height = 20.5; width = 29; return; }
    if (wtran == "projstandardcssyellowcad") { height = 19.0; width = 28; return; }
    if (wtran == "projstandardcssyellowpsq") { height = 20.5; width = 29; return; }
    if (wtran == "projstandardcssgraycad") { height = 19.0; width = 28; return; }
    if (wtran == "projstandardcssgraypsq") { height = 20.5; width = 29; return; }
    if (wtran == "aivdtcad") { height = 12; width = 22; return; }
    if (wtran == "aivdtpsq") { height = 18; width = 22; return; }
    if (wtran == "assetcad") { height = 22; width = 29; return; }
    if (wtran == "assetpsq") { height = 22; width = 29; return; }
    if (wtran == "assetvhwagcad") { height = 22; width = 29; return; }
    if (wtran == "assetvhwagpsq") { height = 22; width = 29; return; }
    if (wtran == "assetvhengcad") { height = 22; width = 29; return; }
    if (wtran == "assetvhengpsq") { height = 22; width = 29; return; }
    if (wtran == "assetvhauxcad") { height = 22; width = 29; return; }
    if (wtran == "assetvhauxpsq") { height = 22; width = 29; return; }
    if (wtran == "assetvhpaxcad") { height = 22; width = 29; return; }
    if (wtran == "assetvhpaxpsq") { height = 22; width = 29; return; }
    if (wtran == "assetvhrdvcad") { height = 22; width = 29; return; }
    if (wtran == "assetvhrdvpsq") { height = 22; width = 29; return; }
    if (wtran == "assetinvascad") { height = 22; width = 29; return; }
    if (wtran == "assetinvaspsq") { height = 22; width = 29; return; }
    if (wtran == "asseteqgptcad") { height = 22; width = 29; return; }
    if (wtran == "asseteqgptpsq") { height = 22; width = 29; return; }
    if (wtran == "assetbldngcad") { height = 22; width = 29; return; }
    if (wtran == "assetbldngpsq") { height = 22; width = 29; return; }
    if (wtran == "assetyrdldcad") { height = 22; width = 29; return; }
    if (wtran == "assetyrdldpsq") { height = 22; width = 29; return; }
    if (wtran == "assetlbdldcad") { height = 22; width = 29; return; }
    if (wtran == "assetlbdldpsq") { height = 22; width = 29; return; }
    if (wtran == "assetmailncad") { height = 22; width = 29; return; }
    if (wtran == "assetmailnpsq") { height = 22; width = 29; return; }
    if (wtran == "assetextlncad") { height = 22; width = 29; return; }
    if (wtran == "assetextlnpsq") { height = 22; width = 29; return; }
    if (wtran == "assetyrdsdcad") { height = 22; width = 29; return; }
    if (wtran == "assetyrdsdpsq") { height = 22; width = 29; return; }
    if (wtran == "assetsidngcad") { height = 22; width = 29; return; }
    if (wtran == "assetsidngpsq") { height = 22; width = 29; return; }
    if (wtran == "assetlvlcrcad") { height = 22; width = 29; return; }
    if (wtran == "assetlvlcrpsq") { height = 22; width = 29; return; }
    if (wtran == "assetovrpscad") { height = 22; width = 29; return; }
    if (wtran == "assetovrpspsq") { height = 22; width = 29; return; }
    if (wtran == "assetundpscad") { height = 22; width = 29; return; }
    if (wtran == "assetundpspsq") { height = 22; width = 29; return; }
    if (wtran == "assetbrdgecad") { height = 22; width = 29; return; }
    if (wtran == "assetbrdgepsq") { height = 22; width = 29; return; }
    if (wtran == "assetviadtcad") { height = 22; width = 29; return; }
    if (wtran == "assetviadtpsq") { height = 22; width = 29; return; }
    if (wtran == "assetculvtcad") { height = 22; width = 29; return; }
    if (wtran == "assetculvtpsq") { height = 22; width = 29; return; }
    if (wtran == "assettunnlcad") { height = 22; width = 29; return; }
    if (wtran == "assettunnlpsq") { height = 22; width = 29; return; }
    if (wtran == "assetsupercad") { height = 22; width = 29; return; }
    if (wtran == "assetsuperpsq") { height = 22; width = 29; return; }
    if (wtran == "assetsupersvcad") { height = 22; width = 29; return; }
    if (wtran == "assetsupersvpsq") { height = 22; width = 29; return; }
    if (wtran == "assetgeocad") { height = 22; width = 29; return; }
    if (wtran == "assetgeopsq") { height = 22; width = 29; return; }
    if (wtran == "invtycad") { height = 22; width = 22; return; }
    if (wtran == "invtypsq") { height = 22; width = 30; return; }
    if (wtran == "invtyedcad") { height = 22; width = 22; return; }
    if (wtran == "invtyedpsq") { height = 22; width = 30; return; }
    if (wtran == "invtyvxcad") { height = 22; width = 22; return; }
    if (wtran == "invtyvxpsq") { height = 22; width = 30; return; }
    if (wtran == "invtyvgcad") { height = 22; width = 22; return; }
    if (wtran == "invtyvgpsq") { height = 22; width = 30; return; }
    if (wtran == "invtylccad") { height = 22; width = 22; return; }
    if (wtran == "invtylcpsq") { height = 22; width = 30; return; }
    if (wtran == "invtylpcad") { height = 22; width = 22; return; }
    if (wtran == "invtylppsq") { height = 22; width = 30; return; }
    if (wtran == "invtylrcad") { height = 22; width = 22; return; }
    if (wtran == "invtylrpsq") { height = 22; width = 30; return; }
    if (wtran == "invtydccad") { height = 22; width = 22; return; }
    if (wtran == "invtydcpsq") { height = 22; width = 30; return; }
    if (wtran == "invtydpcad") { height = 22; width = 22; return; }
    if (wtran == "invtydppsq") { height = 22; width = 30; return; }
    if (wtran == "invtytpcad") { height = 22; width = 22; return; }
    if (wtran == "invtytppsq") { height = 22; width = 30; return; }
    if (wtran == "invtytlcad") { height = 22; width = 22; return; }
    if (wtran == "invtytlpsq") { height = 22; width = 30; return; }
    if (wtran == "invtypncad") { height = 22; width = 22; return; }
    if (wtran == "invtypnpsq") { height = 22; width = 30; return; }
    if (wtran == "invtypscad") { height = 22; width = 22; return; }
    if (wtran == "invtypspsq") { height = 22; width = 30; return; }
    if (wtran == "invtypicad") { height = 22; width = 22; return; }
    if (wtran == "invtypipsq") { height = 22; width = 30; return; }
    if (wtran == "invtyptcad") { height = 22; width = 22; return; }
    if (wtran == "invtyptpsq") { height = 22; width = 30; return; }
    if (wtran == "invtytucad") { height = 22; width = 22; return; }
    if (wtran == "invtytupsq") { height = 22; width = 30; return; }
    if (wtran == "invtyvdcad") { height = 22; width = 22; return; }
    if (wtran == "invtyvdpsq") { height = 22; width = 30; return; }
    if (wtran == "invtybucad") { height = 22; width = 22; return; }
    if (wtran == "invtybupsq") { height = 22; width = 30; return; }
    if (wtran == "prosscad") { height = 22; width = 32; return; }
    if (wtran == "prosspsq") { height = 21; width = 32; return; }
    if (wtran == "prossimcpacad") { height = 22; width = 32; return; }
    if (wtran == "prossimcpapsq") { height = 21; width = 32; return; }
    if (wtran == "prossafatacad") { height = 22; width = 32; return; }
    if (wtran == "prossafatapsq") { height = 21; width = 32; return; }
    if (wtran == "prossmrbxacad") { height = 22; width = 32; return; }
    if (wtran == "prossmrbxapsq") { height = 21; width = 32; return; }
    if (wtran == "prossmrbxpcad") { height = 22; width = 32; return; }
    if (wtran == "prossmrbxppsq") { height = 21; width = 32; return; }
    if (wtran == "prossivgescad") { height = 22; width = 32; return; }
    if (wtran == "prossivgespsq") { height = 21; width = 32; return; }
    if (wtran == "prossivgencad") { height = 22; width = 32; return; }
    if (wtran == "prossivgenpsq") { height = 21; width = 32; return; }
    if (wtran == "prosscomodcad") { height = 22; width = 32; return; }
    if (wtran == "prosscomodpsq") { height = 21; width = 32; return; }
    if (wtran == "obcntprcad") { height = 10; width = 22; return; }
    if (wtran == "obcntprxcad") { height = 10; width = 22; return; }
    if (wtran == "obcntprpsq") { height = 22; width = 23; return; }
    if (wtran == "obcntprxpsq") { height = 22; width = 23; return; }
    if (wtran == "obcntprselcad") { height = 10; width = 22; return; }
    if (wtran == "obcntprselpsq") { height = 22; width = 23; return; }
    if (wtran == "fxprscad") { height = 22; width = 32; return; }
    if (wtran == "fxprspsq") { height = 21; width = 32; return; }
    if (wtran == "fxacocad") { height = 15; width = 20; return; }
    if (wtran == "fxacoxcad") { height = 15; width = 20; return; }
    if (wtran == "fxacopsq") { height = 20; width = 20; return; }
    if (wtran == "fxacoxpsq") { height = 20; width = 20; return; }
    if (wtran == "prhsocad") { height = 15; width = 20; return; }
    if (wtran == "prhsoxcad") { height = 15; width = 20; return; }
    if (wtran == "prhsopsq") { height = 20; width = 20; return; }
    if (wtran == "prhsoxpsq") { height = 20; width = 20; return; }
    if (wtran == "prhsogpcad") { height = 15; width = 20; return; }
    if (wtran == "prhsogpxcad") { height = 15; width = 20; return; }
    if (wtran == "prhsogppsq") { height = 20; width = 20; return; }
    if (wtran == "prhsogpxpsq") { height = 20; width = 20; return; }
    if (wtran == "prhsocontcad") { height = 15; width = 20; return; }
    if (wtran == "prhsocontpsq") { height = 20; width = 20; return; }
    if (wtran == "obdocprcad") { height = 10; width = 22; return; }
    if (wtran == "obdocprxcad") { height = 10; width = 22; return; }
    if (wtran == "obdocprpsq") { height = 22; width = 23; return; }
    if (wtran == "obdocprxpsq") { height = 22; width = 23; return; }
    if (wtran == "obdocpremlcad") { height = 10; width = 22; return; }
    if (wtran == "obdocpremlxcad") { height = 10; width = 22; return; }
    if (wtran == "obdocpremlpsq") { height = 22; width = 23; return; }
    if (wtran == "obdocpremlxpsq") { height = 22; width = 23; return; }
    if (wtran == "obdocrbcad") { height = 10; width = 22; return; }
    if (wtran == "obdocrbpsq") { height = 22; width = 23; return; }
    if (wtran == "pjauscad") { height = 22; width = 32; return; }
    if (wtran == "pjauspsq") { height = 21; width = 32; return; }
    if (wtran == "pjausppaobtvcad") { height = 22; width = 32; return; }
    if (wtran == "pjausppaobtvpsq") { height = 21; width = 32; return; }
    if (wtran == "pjauspaaotcad") { height = 22; width = 32; return; }
    if (wtran == "pjauspaaotpsq") { height = 21; width = 32; return; }
    if (wtran == "pjauspaaopcad") { height = 22; width = 32; return; }
    if (wtran == "pjauspaaoppsq") { height = 21; width = 32; return; }
    if (wtran == "pjauspaaittvcad") { height = 22; width = 32; return; }
    if (wtran == "pjauspaaittvpsq") { height = 21; width = 32; return; }
    if (wtran == "pjauspaaitpscad") { height = 22; width = 32; return; }
    if (wtran == "pjauspaaitpspsq") { height = 21; width = 32; return; }
    if (wtran == "pjauspapuscad") { height = 22; width = 32; return; }
    if (wtran == "pjauspapuspsq") { height = 21; width = 32; return; }
    if (wtran == "pjauspaepbcad") { height = 22; width = 32; return; }
    if (wtran == "pjauspaepbpsq") { height = 21; width = 32; return; }
    if (wtran == "pjauspapsvcad") { height = 22; width = 32; return; }
    if (wtran == "pjauspapsvpsq") { height = 21; width = 32; return; }
    if (wtran == "pjauspaetmcad") { height = 22; width = 32; return; }
    if (wtran == "pjauspaetmpsq") { height = 21; width = 32; return; }
    if (wtran == "obxlspaaittvcad") { height = 10; width = 26; return; }
    if (wtran == "obxlspaaittvpsq") { height = 22; width = 26; return; }
    if (wtran == "obxlspaaitpscad") { height = 10; width = 26; return; }
    if (wtran == "obxlspaaitpspsq") { height = 22; width = 26; return; }
    if (wtran == "obxlspapuscad") { height = 10; width = 26; return; }
    if (wtran == "obxlspapuspsq") { height = 22; width = 26; return; }
    if (wtran == "obxlspaepbcad") { height = 10; width = 26; return; }
    if (wtran == "obxlspaepbpsq") { height = 22; width = 26; return; }
    if (wtran == "obxlspapsvcad") { height = 10; width = 26; return; }
    if (wtran == "obxlspapsvpsq") { height = 22; width = 26; return; }
    if (wtran == "obxlspaetmcad") { height = 10; width = 26; return; }
    if (wtran == "obxlspaetmpsq") { height = 22; width = 26; return; }
    if (wtran == "obxlsppaobtvcad") { height = 10; width = 26; return; }
    if (wtran == "obxlsppaobtvpsq") { height = 22; width = 26; return; }
    if (wtran == "pjaussupercad") { height = 19.0; width = 28; return; }
    if (wtran == "pjaussuperpsq") { height = 20.5; width = 29; return; }
    if (wtran == "obcntpjcad") { height = 10; width = 22; return; }
    if (wtran == "obcntpjxcad") { height = 10; width = 22; return; }
    if (wtran == "obcntpjpsq") { height = 22; width = 23; return; }
    if (wtran == "obcntpjxpsq") { height = 22; width = 23; return; }
    if (wtran == "obcntpjselcad") { height = 10; width = 22; return; }
    if (wtran == "obcntpjselpsq") { height = 22; width = 23; return; }
    if (wtran == "pjhsocad") { height = 15; width = 20; return; }
    if (wtran == "pjhsoxcad") { height = 15; width = 20; return; }
    if (wtran == "pjhsopsq") { height = 20; width = 20; return; }
    if (wtran == "pjhsoxpsq") { height = 20; width = 20; return; }
    if (wtran == "pjhsogpcad") { height = 15; width = 20; return; }
    if (wtran == "pjhsogpxcad") { height = 15; width = 20; return; }
    if (wtran == "pjhsogppsq") { height = 20; width = 20; return; }
    if (wtran == "pjhsogpxpsq") { height = 20; width = 20; return; }
    if (wtran == "pjhsocontcad") { height = 15; width = 20; return; }
    if (wtran == "pjhsocontpsq") { height = 20; width = 20; return; }
    if (wtran == "obdoccad") { height = 10; width = 26; return; }
    if (wtran == "obdocxcad") { height = 10; width = 26; return; }
    if (wtran == "obdocpsq") { height = 22; width = 26; return; }
    if (wtran == "obdocxpsq") { height = 22; width = 26; return; }
    if (wtran == "obdocpjcad") { height = 10; width = 22; return; }
    if (wtran == "obdocpjxcad") { height = 10; width = 22; return; }
    if (wtran == "obdocpjpsq") { height = 22; width = 23; return; }
    if (wtran == "obdocpjxpsq") { height = 22; width = 23; return; }
    if (wtran == "obdocpjcklcad") { height = 10; width = 22; return; }
    if (wtran == "obdocpjcklxcad") { height = 10; width = 22; return; }
    if (wtran == "obdocpjcklpsq") { height = 22; width = 23; return; }
    if (wtran == "obdocpjcklxpsq") { height = 22; width = 23; return; }
    if (wtran == "obdocpjcklopcad") { height = 10; width = 22; return; }
    if (wtran == "obdocpjcklopxcad") { height = 10; width = 22; return; }
    if (wtran == "obdocpjckloppsq") { height = 22; width = 23; return; }
    if (wtran == "obdocpjcklopxpsq") { height = 22; width = 23; return; }
    if (wtran == "obdocpjemlcad") { height = 10; width = 22; return; }
    if (wtran == "obdocpjemlxcad") { height = 10; width = 22; return; }
    if (wtran == "obdocpjemlpsq") { height = 22; width = 23; return; }
    if (wtran == "obdocpjemlxpsq") { height = 22; width = 23; return; }
    if (wtran == "soliccad") { height = 19; width = 24; return; }
    if (wtran == "solicpsq") { height = 19; width = 24; return; }
    if (wtran == "solexcad") { height = 19; width = 24; return; }
    if (wtran == "solexpsq") { height = 19; width = 24; return; }
    if (wtran == "solincad") { height = 19; width = 24; return; }
    if (wtran == "solinpsq") { height = 19; width = 24; return; }
    if (wtran == "areaotcad") { height = 19; width = 24; return; }
    if (wtran == "areaotpsq") { height = 19; width = 24; return; }
    if (wtran == "areaopcad") { height = 19; width = 24; return; }
    if (wtran == "areaoppsq") { height = 19; width = 24; return; }
    if (wtran == "areaiotcad") { height = 19; width = 24; return; }
    if (wtran == "areaiotpsq") { height = 19; width = 24; return; }
    if (wtran == "areaiopcad") { height = 19; width = 24; return; }
    if (wtran == "areaioppsq") { height = 19; width = 24; return; }
    if (wtran == "areaaotcad") { height = 19; width = 24; return; }
    if (wtran == "areaaotpsq") { height = 19; width = 24; return; }
    if (wtran == "areaaopcad") { height = 19; width = 24; return; }
    if (wtran == "areaaoppsq") { height = 19; width = 24; return; }
    if (wtran == "areagotcad") { height = 19; width = 24; return; }
    if (wtran == "areagotpsq") { height = 19; width = 24; return; }
    if (wtran == "areagopcad") { height = 19; width = 24; return; }
    if (wtran == "areagoppsq") { height = 19; width = 24; return; }
    if (wtran == "solctcad") { height = 19; width = 24; return; }
    if (wtran == "solctpsq") { height = 19; width = 24; return; }
    if (wtran == "solctopcad") { height = 19; width = 24; return; }
    if (wtran == "solctoppsq") { height = 19; width = 24; return; }
    if (wtran == "solctotcad") { height = 19; width = 24; return; }
    if (wtran == "solctotpsq") { height = 19; width = 24; return; }
    if (wtran == "solctxopcad") { height = 19; width = 24; return; }
    if (wtran == "solctxoppsq") { height = 19; width = 24; return; }
    if (wtran == "solctxotcad") { height = 19; width = 24; return; }
    if (wtran == "solctxotpsq") { height = 19; width = 24; return; }
    if (wtran == "obxlssolincad") { height = 10; width = 26; return; }
    if (wtran == "obxlssolinpsq") { height = 22; width = 26; return; }
    if (wtran == "obxlssolexcad") { height = 10; width = 26; return; }
    if (wtran == "obxlssolexpsq") { height = 22; width = 26; return; }
    if (wtran == "ixaccstcad") { height = 19; width = 28; return; }
    if (wtran == "ixaccstpsq") { max=1; return; }
    if (wtran == "obxlsaccstcad") { height = 10; width = 26; return; }
    if (wtran == "obxlsaccstpsq") { height = 22; width = 26; return; }
    if (wtran == "ixaclscad") { height = 19; width = 28; return; }
    if (wtran == "ixaclspsq") { max=1; return; }
    if (wtran == "obxlsaclscad") { height = 10; width = 26; return; }
    if (wtran == "obxlsaclspsq") { height = 22; width = 26; return; }
    if (wtran == "pcontacad") { height = 19; width = 28; return; }
    if (wtran == "pcontapsq") { height = 19; width = 22; return; }
    if (wtran == "obxlspcontacad") { height = 10; width = 26; return; }
    if (wtran == "obxlspcontapsq") { height = 22; width = 26; return; }
    if (wtran == "localcad") { height = 19; width = 28; return; }
    if (wtran == "localpsq") { height = 19; width = 22; return; }
    if (wtran == "obxlslocalcad") { height = 10; width = 26; return; }
    if (wtran == "obxlslocalpsq") { height = 22; width = 26; return; }
    if (wtran == "xcategcad") { height = 19; width = 28; return; }
    if (wtran == "xcategpsq") { height = 19; width = 22; return; }
    if (wtran == "ixccustcad") { height = 19; width = 28; return; }
    if (wtran == "ixccustpsq") { height = 19; width = 30; return; }
    if (wtran == "obxlsccustcad") { height = 10; width = 26; return; }
    if (wtran == "obxlsccustpsq") { height = 22; width = 26; return; }
    if (wtran == "obxlscategcad") { height = 10; width = 26; return; }
    if (wtran == "obxlscategpsq") { height = 22; width = 26; return; }
    if (wtran == "sqassetlinecad") { height = 19; width = 28; return; }
    if (wtran == "sqassetlinepsq") { max=1; return; }
    if (wtran == "ixabastecimentocad") { height = 19; width = 28; return; }
    if (wtran == "ixabastecimentopsq") { max=1; return; }
    if (wtran == "ixlocodesempcad") { height = 19; width = 28; return; }
    if (wtran == "ixlocodesemppsq") { max=1; return; }
    if (wtran == "ixlocomanutcad") { height = 19; width = 28; return; }
    if (wtran == "ixlocomanutpsq") { max=1; return; }
    if (wtran == "ixvagaodesempcad") { height = 19; width = 28; return; }
    if (wtran == "ixvagaodesemppsq") { max=1; return; }
    if (wtran == "ixvagaomanutcad") { height = 19; width = 28; return; }
    if (wtran == "ixvagaomanutpsq") { max=1; return; }
    if (wtran == "ixvagaosislogcad") { height = 19; width = 28; return; }
    if (wtran == "ixvagaosislogpsq") { max=1; return; }
    if (wtran == "ixvagaodispcad") { height = 19; width = 28; return; }
    if (wtran == "ixvagaodisppsq") { max=1; return; }
    if (wtran == "ixvagaoprodcad") { height = 19; width = 28; return; }
    if (wtran == "ixvagaoprodpsq") { max=1; return; }
    if (wtran == "ixtremformadocad") { height = 19; width = 28; return; }
    if (wtran == "ixtremformadopsq") { max=1; return; }
    if (wtran == "ixtremdesempcad") { height = 19; width = 28; return; }
    if (wtran == "ixtremdesemppsq") { max=1; return; }
    if (wtran == "ixvagaomanutultmcad") { height = 19; width = 28; return; }
    if (wtran == "ixvagaomanutultmpsq") { max=1; return; }
    if (wtran == "ixativofixocad") { height = 19; width = 28; return; }
    if (wtran == "ixativofixopsq") { max=1; return; }
    if (wtran == "ixativofixoporlocalcad") { height = 19; width = 28; return; }
    if (wtran == "ixativofixoporlocalpsq") { max=1; return; }
    if (wtran == "ixativofixoporcatgcad") { height = 19; width = 28; return; }
    if (wtran == "ixativofixoporcatgpsq") { max=1; return; }
    if (wtran == "ixativofixoadicaocad") { height = 19; width = 28; return; }
    if (wtran == "ixativofixoadicaopsq") { max=1; return; }
    if (wtran == "ixativofixoatualizacad") { height = 19; width = 28; return; }
    if (wtran == "ixativofixoatualizapsq") { max=1; return; }
    if (wtran == "ixativofixobaixacad") { height = 19; width = 28; return; }
    if (wtran == "ixativofixobaixapsq") { max=1; return; }
    if (wtran == "ixabastecimentoferrcad") { height = 19; width = 28; return; }
    if (wtran == "ixabastecimentoferrpsq") { max=1; return; }
    if (wtran == "ixtremformadomerccad") { height = 19; width = 28; return; }
    if (wtran == "ixtremformadomercpsq") { max=1; return; }
    if (wtran == "obxlscad") { height = 10; width = 26; return; }
    if (wtran == "obxlspsq") { height = 22; width = 26; return; }
    if (wtran == "obxlsassetcad") { height = 10; width = 26; return; }
    if (wtran == "obxlsassetpsq") { height = 22; width = 26; return; }
    if (wtran == "obxlsafixocad") { height = 10; width = 26; return; }
    if (wtran == "obxlsafixopsq") { height = 22; width = 26; return; }
    if (wtran == "obxlsafbxacad") { height = 10; width = 26; return; }
    if (wtran == "obxlsafbxapsq") { height = 22; width = 26; return; }
    if (wtran == "obxlsobdocxcad") { height = 10; width = 26; return; }
    if (wtran == "obxlsobdocxpsq") { height = 22; width = 26; return; }
    if (wtran == "obxlsobdoccad") { height = 10; width = 26; return; }
    if (wtran == "obxlsobdocpsq") { height = 22; width = 26; return; }
    if (wtran == "obxlslcdspcad") { height = 10; width = 26; return; }
    if (wtran == "obxlslcdsppsq") { height = 22; width = 26; return; }
    if (wtran == "obxlslcmntcad") { height = 10; width = 26; return; }
    if (wtran == "obxlslcmntpsq") { height = 22; width = 26; return; }
    if (wtran == "obxlsvgdspcad") { height = 10; width = 26; return; }
    if (wtran == "obxlsvgdsppsq") { height = 22; width = 26; return; }
    if (wtran == "obxlsvgdiscad") { height = 10; width = 26; return; }
    if (wtran == "obxlsvgdispsq") { height = 22; width = 26; return; }
    if (wtran == "obxlsvgmntcad") { height = 10; width = 26; return; }
    if (wtran == "obxlsvgmntpsq") { height = 22; width = 26; return; }
    if (wtran == "obxlsvgmnucad") { height = 10; width = 26; return; }
    if (wtran == "obxlsvgmnupsq") { height = 22; width = 26; return; }
    if (wtran == "obxlsvgprdcad") { height = 10; width = 26; return; }
    if (wtran == "obxlsvgprdpsq") { height = 22; width = 26; return; }
    if (wtran == "obxlsvgslgcad") { height = 10; width = 26; return; }
    if (wtran == "obxlsvgslgpsq") { height = 22; width = 26; return; }
    if (wtran == "obxlsabastcad") { height = 10; width = 26; return; }
    if (wtran == "obxlsabastpsq") { height = 22; width = 26; return; }
    if (wtran == "obxlstrdspcad") { height = 10; width = 26; return; }
    if (wtran == "obxlstrdsppsq") { height = 22; width = 26; return; }
    if (wtran == "obxlstrfrmcad") { height = 10; width = 26; return; }
    if (wtran == "obxlstrfrmpsq") { height = 22; width = 26; return; }
    if (wtran == "obxlsafadccad") { height = 10; width = 26; return; }
    if (wtran == "obxlsafadcpsq") { height = 22; width = 26; return; }
    if (wtran == "obxlsafatucad") { height = 10; width = 26; return; }
    if (wtran == "obxlsafatupsq") { height = 22; width = 26; return; }
    if (wtran == "importsqcad") { height = 5; width = 17; return; }
    if (wtran == "importsqpsq") { height = 16.4; width = 28; return; }
    if (wtran == "importafcad") { height = 5; width = 17; return; }
    if (wtran == "importafpsq") { height = 16.4; width = 28; return; }
    if (wtran == "importatcad") { height = 5; width = 17; return; }
    if (wtran == "importatpsq") { height = 16.4; width = 28; return; }
    if (wtran == "impexcfgcad") { height = 5; width = 17; return; }
    if (wtran == "impexcfgpsq") { height = 16.4; width = 28; return; }
    if (wtran == "impexcad") { height = 11; width = 22; return; }
    if (wtran == "impexpsq") { height = 19.0; width = 28; return; }
    if (wtran == "convscad") { height = 11; width = 22; return; }
    if (wtran == "convsxcad") { height = 11; width = 22; return; }
    if (wtran == "convspsq") { height = 19; width = 26; return; }
    if (wtran == "convsxpsq") { height = 19; width = 26; return; }
    if (wtran == "implgcad") { height = 19; width = 28; return; }
    if (wtran == "implgpsq") { height = 19.0; width = 28; return; }
    if (wtran == "impldcad") { height = 19; width = 28; return; }
    if (wtran == "impldxcad") { height = 19; width = 28; return; }
    if (wtran == "impldpsq") { height = 19; width = 26; return; }
    if (wtran == "impldxpsq") { height = 19; width = 26; return; }
    if (wtran == "paramcad") { height = 11; width = 22; return; }
    if (wtran == "parampsq") { height = 19.0; width = 28; return; }
    if (wtran == "dctblcad") { height = 11; width = 22; return; }
    if (wtran == "dctblpsq") { height = 19.0; width = 28; return; }
    if (wtran == "dctlncad") { height = 11; width = 22; return; }
    if (wtran == "dctlnxcad") { height = 11; width = 22; return; }
    if (wtran == "dctlnpsq") { height = 19; width = 26; return; }
    if (wtran == "dctlnxpsq") { height = 19; width = 26; return; }
    if (wtran == "stdtxcad") { height = 18; width = 21; return; }
    if (wtran == "stdtxpsq") { height = 16.4; width = 26; return; }
    if (wtran == "mpgeocad") { max=1; return; }
    if (wtran == "mpgeopsq") { max=1; return; }
    if (wtran == "mpgeoeditcad") { max=1; return; }
    if (wtran == "mpgeoeditpsq") { max=1; return; }
    if (wtran == "obocpcad") { height = 10; width = 26; return; }
    if (wtran == "obocpxcad") { height = 10; width = 26; return; }
    if (wtran == "obocppsq") { height = 22; width = 26; return; }
    if (wtran == "obocpxpsq") { height = 22; width = 26; return; }
    if (wtran == "obocrcad") { height = 10; width = 26; return; }
    if (wtran == "obocrxcad") { height = 10; width = 26; return; }
    if (wtran == "obocrpsq") { height = 22; width = 26; return; }
    if (wtran == "obocrxpsq") { height = 22; width = 26; return; }
    if (wtran == "obmaccad") { height = 10; width = 26; return; }
    if (wtran == "obmacxcad") { height = 10; width = 26; return; }
    if (wtran == "obmacpsq") { height = 22; width = 26; return; }
    if (wtran == "obmacxpsq") { height = 22; width = 26; return; }
    if (wtran == "obaedcad") { height = 10; width = 26; return; }
    if (wtran == "obaedxcad") { height = 10; width = 26; return; }
    if (wtran == "obaedpsq") { height = 22; width = 26; return; }
    if (wtran == "obaedxpsq") { height = 22; width = 26; return; }
    if (wtran == "obaedestcad") { height = 10; width = 26; return; }
    if (wtran == "obaedestxcad") { height = 10; width = 26; return; }
    if (wtran == "obaedestpsq") { height = 22; width = 26; return; }
    if (wtran == "obaedestxpsq") { height = 22; width = 26; return; }
    if (wtran == "obaedrvecad") { height = 10; width = 26; return; }
    if (wtran == "obaedrvexcad") { height = 10; width = 26; return; }
    if (wtran == "obaedrvepsq") { height = 22; width = 26; return; }
    if (wtran == "obaedrvexpsq") { height = 22; width = 26; return; }
    if (wtran == "obaedrvicad") { height = 10; width = 26; return; }
    if (wtran == "obaedrvixcad") { height = 10; width = 26; return; }
    if (wtran == "obaedrvipsq") { height = 22; width = 26; return; }
    if (wtran == "obaedrvixpsq") { height = 22; width = 26; return; }
    if (wtran == "obaedcobcad") { height = 10; width = 26; return; }
    if (wtran == "obaedcobxcad") { height = 10; width = 26; return; }
    if (wtran == "obaedcobpsq") { height = 22; width = 26; return; }
    if (wtran == "obaedcobxpsq") { height = 22; width = 26; return; }
    if (wtran == "obaedesqcad") { height = 10; width = 26; return; }
    if (wtran == "obaedesqxcad") { height = 10; width = 26; return; }
    if (wtran == "obaedesqpsq") { height = 22; width = 26; return; }
    if (wtran == "obaedesqxpsq") { height = 22; width = 26; return; }
    if (wtran == "obaedstecad") { height = 10; width = 26; return; }
    if (wtran == "obaedstexcad") { height = 10; width = 26; return; }
    if (wtran == "obaedstepsq") { height = 22; width = 26; return; }
    if (wtran == "obaedstexpsq") { height = 22; width = 26; return; }
    if (wtran == "obaedstacad") { height = 10; width = 26; return; }
    if (wtran == "obaedstaxcad") { height = 10; width = 26; return; }
    if (wtran == "obaedstapsq") { height = 22; width = 26; return; }
    if (wtran == "obaedstaxpsq") { height = 22; width = 26; return; }
    if (wtran == "obaedesgcad") { height = 10; width = 26; return; }
    if (wtran == "obaedesgxcad") { height = 10; width = 26; return; }
    if (wtran == "obaedesgpsq") { height = 22; width = 26; return; }
    if (wtran == "obaedesgxpsq") { height = 22; width = 26; return; }
    if (wtran == "obimgcad") { max=1; return; }
    if (wtran == "obimgxcad") { max=1; return; }
    if (wtran == "obimgpsq") { height = 22; width = 26; return; }
    if (wtran == "obimgxpsq") { height = 22; width = 26; return; }
    if (wtran == "obimgpjcad") { max=1; return; }
    if (wtran == "obimgpjxcad") { max=1; return; }
    if (wtran == "obimgpjpsq") { height = 19.4; width = 29; return; }
    if (wtran == "obimgpjxpsq") { height = 19.4; width = 29; return; }
    if (wtran == "codfcad") { height = 18; width = 22; return; }
    if (wtran == "codfpsq") { height = 16; width = 24; return; }
    if (wtran == "codfmszcad") { height = 18; width = 22; return; }
    if (wtran == "codfmszpsq") { height = 16; width = 24; return; }
    if (wtran == "codfmntcad") { height = 10; width = 19; return; }
    if (wtran == "codfmntxcad") { height = 10; width = 19; return; }
    if (wtran == "codfmntpsq") { height = 20; width = 24; return; }
    if (wtran == "codfmntxpsq") { height = 20; width = 24; return; }
    if (wtran == "gnlngmntcad") { height = 08; width = 22; return; }
    if (wtran == "gnlngmntpsq") { height = 16; width = 28; return; }
    if (wtran == "langcad") { height = 5; width = 17; return; }
    if (wtran == "langpsq") { height = 16.4; width = 28; return; }
    if (wtran == "orgzncad") { height = 5; width = 17; return; }
    if (wtran == "orgznpsq") { height = 16.4; width = 28; return; }
    if (wtran == "helpmaintcad") { max=1; return; }
    if (wtran == "helpmaintpsq") { max=1; return; }
    if (wtran == "helpcad") { height = 20.0; width = 28.0; return; }
    if (wtran == "helppsq") { max=1; return; }
    if (wtran == "helpvwcad") { height = 20.0; width = 28.0; return; }
    if (wtran == "helpvwpsq") { max=1; return; }
    if (wtran == "helprcad") { height = 8; width = 28; return; }
    if (wtran == "helprxcad") { height = 8; width = 28; return; }
    if (wtran == "helprpsq") { height = 18; width = 28; return; }
    if (wtran == "helprxpsq") { height = 18; width = 28; return; }
    if (wtran == "helprvwcad") { height = 8; width = 28; return; }
    if (wtran == "helprvwpsq") { height = 18; width = 28; return; }
    if (wtran == "helprsearchvwcad") { height = 20.0; width = 28.0; return; }
    if (wtran == "helprsearchvwpsq") { max=1; return; }
    if (wtran == "helpsearchcad") { max=1; return; }
    if (wtran == "helpsearchpsq") { height = 18; width = 28; return; }
    if (wtran == "helpsearchvwcad") { height = 20.0; width = 28.0; return; }
    if (wtran == "helpsearchvwpsq") { max=1; return; }
    if (wtran == "helpsearchtranscad") { max=1; return; }
    if (wtran == "helpsearchtranspsq") { height = 18; width = 26; return; }
    if (wtran == "helppuscad") { height = 20.0; width = 28.0; return; }
    if (wtran == "helppuspsq") { height = 18; width = 24; return; }
    if (wtran == "helpgnscad") { height = 20.0; width = 28.0; return; }
    if (wtran == "helpgnspsq") { height = 18; width = 24; return; }
    if (wtran == "helpgnrcad") { height = 20.0; width = 28.0; return; }
    if (wtran == "helpgnrpsq") { height = 18; width = 24; return; }
    if (wtran == "helpcmscad") { height = 20.0; width = 28.0; return; }
    if (wtran == "helpcmspsq") { height = 18; width = 24; return; }
    if (wtran == "helpcmrcad") { height = 20.0; width = 28.0; return; }
    if (wtran == "helpcmrpsq") { height = 18; width = 24; return; }
    if (wtran == "helpdtscad") { height = 20.0; width = 28.0; return; }
    if (wtran == "helpdtspsq") { height = 18; width = 24; return; }
    if (wtran == "helpdtrcad") { height = 20.0; width = 28.0; return; }
    if (wtran == "helpdtrpsq") { height = 18; width = 24; return; }
    if (wtran == "mesgcad") { height = 18; width = 28; return; }
    if (wtran == "mesgpsq") { height = 18; width = 28; return; }
    if (wtran == "mssgcad") { height = 18; width = 21; return; }
    if (wtran == "mssgpsq") { height = 16.4; width = 26; return; }
    if (wtran == "zmenuassetcad") { height = 13; width = 22; return; }
    if (wtran == "zmenuassetpsq") { height = 18.0; width = 28; return; }
    if (wtran == "zmenuassetbpcad") { height = 13; width = 22; return; }
    if (wtran == "zmenuassetbppsq") { height = 18.0; width = 28; return; }
    if (wtran == "zmenuassetbpadmcad") { height = 13; width = 22; return; }
    if (wtran == "zmenuassetbpadmpsq") { height = 18.0; width = 28; return; }
    if (wtran == "zmenuprosscad") { height = 13; width = 22; return; }
    if (wtran == "zmenuprosspsq") { height = 18.0; width = 28; return; }
    if (wtran == "zmenuinterfacescad") { height = 13; width = 22; return; }
    if (wtran == "zmenuinterfacespsq") { height = 18.0; width = 28; return; }
    if (wtran == "zmenupjauscad") { height = 13; width = 22; return; }
    if (wtran == "zmenupjauspsq") { height = 18.0; width = 28; return; }
    if (wtran == "zmenupjausopcad") { height = 13; width = 22; return; }
    if (wtran == "zmenupjausoppsq") { height = 18.0; width = 28; return; }
    if (wtran == "zmenupjausancad") { height = 13; width = 22; return; }
    if (wtran == "zmenupjausanpsq") { height = 18.0; width = 28; return; }
    if (wtran == "zmenupjausslcad") { height = 13; width = 22; return; }
    if (wtran == "zmenupjausslpsq") { height = 18.0; width = 28; return; }
    if (wtran == "zmenuadmincad") { height = 13; width = 22; return; }
    if (wtran == "zmenuadminpsq") { height = 18.0; width = 28; return; }
    if (wtran == "zrolebpmadmcad") { height = 18; width = 22; return; }
    if (wtran == "zrolebpmadmpsq") { height = 16.4; width = 28; return; }
    if (wtran == "zrolebpmgescad") { height = 18; width = 22; return; }
    if (wtran == "zrolebpmgespsq") { height = 16.4; width = 28; return; }
    if (wtran == "zrolebpminfcad") { height = 18; width = 22; return; }
    if (wtran == "zrolebpminfpsq") { height = 16.4; width = 28; return; }
    if (wtran == "zroleitfgescad") { height = 18; width = 22; return; }
    if (wtran == "zroleitfgespsq") { height = 16.4; width = 28; return; }
    if (wtran == "zrolesisadmcad") { height = 18; width = 22; return; }
    if (wtran == "zrolesisadmpsq") { height = 16.4; width = 28; return; }
    if (wtran == "zrolepjagescad") { height = 18; width = 22; return; }
    if (wtran == "zrolepjagespsq") { height = 16.4; width = 28; return; }
    if (wtran == "zrolepjaotgcad") { height = 18; width = 22; return; }
    if (wtran == "zrolepjaotgpsq") { height = 16.4; width = 28; return; }
    if (wtran == "zrolepjaotacad") { height = 18; width = 22; return; }
    if (wtran == "zrolepjaotapsq") { height = 16.4; width = 28; return; }
    if (wtran == "zrolepjaopgcad") { height = 18; width = 22; return; }
    if (wtran == "zrolepjaopgpsq") { height = 16.4; width = 28; return; }
    if (wtran == "zrolepjaopscad") { height = 18; width = 22; return; }
    if (wtran == "zrolepjaopspsq") { height = 16.4; width = 28; return; }
    if (wtran == "emailcad") { height = 20; width = 28; return; }
    if (wtran == "emailpsq") { max=1; return; }
    if (wtran == "emdstcad") { height = 19; width = 28; return; }
    if (wtran == "emdstpsq") { height = 16.4; width = 28; return; }
    if (wtran == "userxcad") { height = 12; width = 22; return; }
    if (wtran == "userxpsq") { max=1; return; }
    if (wtran == "userpwcad") { height = 7.3; width = 16.0; return; }
    if (wtran == "userpwpsq") { height = 19.0; width = 22; return; }
    if (wtran == "accrcad") { height = 6.0; width = 22; return; }
    if (wtran == "accrpsq") { height = 18.0; width = 22; return; }
    if (wtran == "transcad") { height = 8; width = 22; return; }
    if (wtran == "transpsq") { height = 20; width = 31; return; }
    if (wtran == "transcodfcad") { height = 8; width = 22; return; }
    if (wtran == "transcodfpsq") { height = 20; width = 31; return; }
    if (wtran == "transmenucad") { height = 8; width = 22; return; }
    if (wtran == "transmenupsq") { height = 20; width = 31; return; }
    if (wtran == "rolecad") { height = 6.0; width = 19.0;; return; }
    if (wtran == "rolepsq") { height = 18; width = 28; return; }
    if (wtran == "rloprcad") { height = 8.0; width = 28.0; return; }
    if (wtran == "rloprpsq") { max=1; return; }
    if (wtran == "rloprmntcad") { height = 18; width = 22; return; }
    if (wtran == "rloprmntpsq") { height = 16.4; width = 28; return; }
    if (wtran == "rloprcodfcad") { height = 8.0; width = 28.0; return; }
    if (wtran == "rloprcodfxcad") { height = 8.0; width = 28.0; return; }
    if (wtran == "rloprcodfpsq") { max=1; return; }
    if (wtran == "rloprcodfxpsq") { max=1; return; }
    if (wtran == "rolecopyselcad") { height = 18; width = 22; return; }
    if (wtran == "rolecopyselpsq") { height = 16.4; width = 28; return; }
} // winsizedir end 
